backend:
  name: github
  repo: mo6moming/ReactCMSTest
  branch: master

media_folder: "img/uploads"

collections:
  - name: "products"
    label: "Products"
    folder: "_products"
    slug: "{{slug}}"
    create: true
    fields:
        - {label: "SKU", name: "sku", widget: "string" }
        - {label: "Price", name: "price", widget: "number"}
        - {label: "Image", name: "image", widget: "string"}
        - {label: "Body", name: "body", widget: "string"}
        - {label: "Slug", name: "slug", widget: "string" }
        - {label: "Layout", name: "layout", widget: "hidden", default: "productdetails"}

exclude:
 - admin/admin.js
 - webpack.config.js
 - package.json
 - README.md
